### ISSUE TITLE
Differances

### ISSUE THREAD

**Issue by gcharles81** [schuppeste/RA8875Ada-BTE#2]
Hello and Thanks for the only working example for SPI flash on the whole web 

 I would like to know what is the differences between this Lib RA8875Ada-BTE and the other one Adafruit_RA8875-Flash-BTE , 

the reason I am asking is because with RA8875Ada-BTE I can use the dispicown function and work with most of the images but some images strangely show horizontal white lines.

I thought RA8875-Flash-BTE is an improved version but the library cannot compile seems that .h file is not compatible 
  Thanks Charles

**Comment by schuppeste** [comment]
Hi, thanks for your Information.

I have tested the Library today in the newest Arduino IDE, 
I found a forgotton Semicolon in the Example, but it compiled. 

Maybe more Information? I don't know what I did in this moment.

Phil

**Comment by gcharles81** [comment]
Hello Thanks for your quick reply I have found the  Semicolon in the Example earlier 

The problem I have is that it seems that all the new functions you have added are not defined in the .h file on the git I have the following errors

flash_to_ram:30: error: 'class Adafruit_RA8875' has no member named 'Transparent_Mode'

   tft.Transparent_Mode();

       ^

flash_to_ram:31: error: 'class Adafruit_RA8875' has no member named 'writeTo'

   tft.writeTo(2);

       ^

flash_to_ram:33: error: 'class Adafruit_RA8875' has no member named 'dispic'

   tft.dispic(1);

       ^

flash_to_ram:34: error: 'class Adafruit_RA8875' has no member named 'dispicown'

   tft.dispicown(0, 0, 480, 232, 0); //Dispicown(startx,starty,width,height, Flashadress)

       ^

exit status 1
'class Adafruit_RA8875' has no member named 'Transparent_Mode'

**Comment by schuppeste** [comment]
okay, now i see the problem..

i should look Backups.. any Problem by Upload file selection..

Sorry, dont know at this moment.. i see it Weekend.

**Comment by schuppeste** [comment]
updated the Flash-BTE Library, untested.

Please test, i have no test equipment.

https://github.com/schuppeste/Adafruit_RA8875-Flash-BTE/blob/master/AdafruitRA8875FlashBTE.zip

The ZIP is different to the live Github content.

**Comment by gcharles81** [comment]
Hello Thanks for the upload - now lib complies and tested working Fine - Again thanks for the effort
